spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cloud:
    gcp:
      storage:
        credentials:
          location: ${LOCATION}
        bucket: ${BUCKET}
        project-id: ${PROJECT_ID}
logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

---


server:
  port: 8443
  servlet:
    session:
      cookie:
        same-site: none # 세션ID가 담긴 쿠키의 same-site 설정을 none 으로 한다.
spring:
  profiles:
    active: pro

  jpa:
    hibernate:
      ddl-auto: validate
---

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none # 세션ID가 담긴 쿠키의 same-site 설정을 none 으로 한다.
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
